version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: railsapp
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - railsapp-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - railsapp-redis:/var/lib/redis/data

  railsapp:
    build:
      context: .
    deploy:
      replicas: 3
      mode: dnsrr
    ports: 
      - "8010"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  sidekiq:
    image: codingexampleapp-railsapp:latest
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
      - railsapp
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes: 
      - ./reverse-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - railsapp

volumes:
  railsapp-postgres:
  railsapp-redis: