version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: railsapp
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - railsapp-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - railsapp-redis:/var/lib/redis/data

  railsapp:
    build:
      context: .
    volumes:
      - .:/opt/app
    ports:
      - '8010'
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/nginx.conf:ro
    links:
      - railsapp
    depends_on:
      - railsapp
    ports:
      - '8020:8020'

volumes:
  railsapp-postgres:
  railsapp-redis: